playbooks/base/first_steps.yml, roles/base/first_steps/defaults/main.yml, roles/base/first_steps/tasks/firststeps.yml, roles/base/first_steps/tasks/main.yml, roles/base/first_steps/tasks/skip_fs.yml
- change first_steps playbook to call corresponding role properly
- change first_steps role
- sla checking with uri module
- remove password change from first steps
- enable fips mode through dict only
- restart after fips mode change detected
=> fix: base/first_steps 

playbooks/base/change_admin_password.yml, roles/base/change_admin_password/defaults/main.yml, roles/base/change_admin_password/meta/main.yml, roles/base/change_admin_password/tasks/main.yml
playbook:
- add request for parameters [old_password, new_password]
role:
- add help message
- change password + reset isam connection + commit change with new_password
=> Fix: change_admin_password

playbooks/base/activate_modules.yml, roles/base/activate_modules/defaults/main.yml, roles/base/activate_modules/tasks/main.yml
playbook:
- add request for parameters [old_password, new_password]
role:
- add help message
- change password + reset isam connection + commit change with new_password
=> Fix: activate_modules

playbooks/base/create_ssl_certificate_databases.yml, roles/base/create_ssl_certificate_databases/defaults/main.yml, roles/base/create_ssl_certificate_databases/tasks/main.yml
playbook:
role:
- add help message
- add filter kdb_name to limit execution at runtime
=> Fix: create_ssl_certificate_databases

playbooks/web/configure_policyserver.yml, roles/web/configure_policyserver/defaults/main.yml, roles/web/configure_policyserver/tasks/main.yml
playbook:
role:
- add help message
- remove connectivity update (should be done in a seperate role)
=> Fix: configure_policyserver

playbooks/base/set_password_sysaccounts.yml, roles/base/set_password_sysaccounts/defaults/main.yml, roles/base/set_password_sysaccounts/meta/main.yml, roles/base/set_password_sysaccounts/tasks/main.yml
playbook:
- modified role path
role:
- help message
- adding filter for user id's  to limit execution at runtime
- change loop label to contain only the user id
=> Fix: set_password_sysaccounts

playbooks/base/publish.yml, roles/base/publish/defaults/main.yml, roles/base/publish/meta/main.yml, roles/base/publish/tasks/main.yml
+ playbook for calling role
+ role incl. help message
=> Added role publish for docker

playbooks/base/configure_time.yml, roles/base/configure_time/tasks/main.yml
playbook:
- remove example (moved to role function -e help=True)
role:
- adding help message
=> Fix: configure_time

playbooks/web/configure_reverseproxy_instances.yml, roles/web/configure_reverseproxy_instances/defaults/main.yml, roles/web/configure_reverseproxy_instances/tasks/main.yml
playbook:
role:
- help message
- improved filter mechanism
- added delete,set feature for entire stanza_id
- modified filter path to match ansible collection restrictions <namespace>.<name>.<filter>
=> Fix: configure_reverseproxy_instances

playbooks/web/configure_management_root.yml, roles/web/configure_management_root/defaults/main.yml, roles/web/configure_management_root/tasks/include_delete_management_root_contents.yml, roles/web/configure_management_root/tasks/include_export_management_root.yml, roles/web/configure_management_root/tasks/include_import_management_root.yml, roles/web/configure_management_root/tasks/include_sync_management_root.yml, roles/web/configure_management_root/tasks/main.yml
playbook:
role:
- help message
- improved filter mechanism
- added export_zip function
- modified filter path to match ansible collection restrictions <namespace>.<name>.<filter>
=> Fix + Feature: configure_management_root

roles/web/configure_management_root/defaults/main.yml, roles/web/configure_management_root/tasks/main.yml
BugFix:
- missing mgmt_action filter for delete task
+ skip multiple imports or just a single one
+ skip multiple exports or just a single one
+ skip_sync
=> BugFix+Feature: improved skip functionality

playbooks/aac/configure_runtime_template_root.yml, roles/aac/configure_runtime_template_root/defaults/main.yml, roles/aac/configure_runtime_template_root/tasks/include_export_runtime_template_root.yml, roles/aac/configure_runtime_template_root/tasks/include_import_runtime_template_root.yml, roles/aac/configure_runtime_template_root/tasks/include_sync_runtime_template_root.yml, roles/aac/configure_runtime_template_root/tasks/main.yml
playbook:
- remove gather_facts to allow to pull server information (e.g. ansible_date_time)
role:
- help message
- improved filter mechanism
- added delete, export_zip functionality
- modified filter path to match ansible collection restrictions <namespace>.<name>.<filter>
=> Fix: configure_runtime_template_root

roles/aac/set_pwd_user_registry/defaults/main.yml, roles/aac/set_pwd_user_registry/meta/main.yml, roles/aac/set_pwd_user_registry/tasks/main.yml, roles/aac/set_server_connection_ldap/defaults/main.yml, roles/aac/set_server_connection_ldap/meta/main.yml, roles/aac/set_server_connection_ldap/tasks/main.yml, roles/fed/get_a_fed_partner/defaults/main.yml, roles/fed/get_a_fed_partner/meta/main.yml, roles/fed/get_a_fed_partner/tasks/main.yml, roles/fed/get_point_of_contact/defaults/main.yml, roles/fed/get_point_of_contact/meta/main.yml, roles/fed/get_point_of_contact/tasks/main.yml, roles/fed/get_sts_chains/defaults/main.yml, roles/fed/get_sts_chains/meta/main.yml, roles/fed/get_sts_chains/tasks/main.yml, roles/fed/import_metadata/defaults/main.yml, roles/fed/import_metadata/meta/main.yml, roles/fed/import_metadata/tasks/main.yml
aac/set_pwd_user_registry
aac/set_pwd_user_registry
fed/get_a_fed_partner
fed/get_point_of_contact
fed/get_sts_chains
fed/import_metadata
=> New roles added to aac and fed:

playbooks/base/configure_static_routes.yml, roles/base/configure_static_routes/defaults/main.yml, roles/base/configure_static_routes/meta/main.yml, roles/base/configure_static_routes/tasks/main.yml
playbook & role to configure (set/add/update/delete) static routes
Role includes new help message
=> New Role+Playbook: configure_static_routes

roles/common_handlers/defaults/main.yml, roles/common_handlers/handlers/main.yml
Added handler for publish changes on Docker.
=> Changes to make roles Docker friendly

roles/aac/configure_access_control_attributes/molecule/add/verify.yml, roles/aac/configure_access_control_attributes/molecule/update/verify.yml
references to get_access_control_attribute are updated to get_access_control_attributes
=> Fix: in configure_access_control_attributes verify.yml

playbooks/base/set_host_records.yml
=> Fix: set_host_records

playbooks/base/backup_firmware.yml, roles/base/backup_firmware/tasks/main.yml
playbook:
role:
- help message
=> Fix: backup_firmware

playbooks/base/configure_dhcp.yml, roles/base/configure_dhcp/defaults/main.yml, roles/base/configure_dhcp/tasks/main.yml
playbook:
role:
- help message
- filter at runtime for interface label
=> Fix: configure_dhcp

playbooks/base/configure_runtime_tunings.yml, roles/base/configure_runtime_tunings/defaults/main.yml, roles/base/configure_runtime_tunings/tasks/main.yml
playbook:
role:
- help message
- typo correction for dict runtime_tunings
- filter for runtime_action
=> Fix: configure_runtime_tunings

playbooks/base/configure_sysaccounts.yml, playbooks/base/create_sysaccounts.yml, roles/base/configure_sysaccounts/defaults/main.yml, roles/base/configure_sysaccounts/meta/main.yml, roles/base/configure_sysaccounts/tasks/main.yml, roles/base/create_sysaccounts/defaults/main.yml, roles/base/create_sysaccounts/tasks/main.yml
playbook:
- new playbook: configure_sysaccounts
role:
- help message
- improved filter mechanism
- new role: configure_sysaccounts
=> Fix+role/playbook: create_sysaccounts + configure_sysaccounts

playbooks/base/set_listening_interfaces.yml, roles/base/set_listening_interfaces/tasks/main.yml
playbook:
role:
- help message
-
=> Fix: set_listening_interfaces

playbooks/web/configure_http_transformation_rules.yml, roles/web/configure_http_transformation_rules/defaults/main.yml, roles/web/configure_http_transformation_rules/meta/main.yml, roles/web/configure_http_transformation_rules/tasks/main.yml
playbook with correct role path
role with help message
=> NewTask: configure_http_transformation_rules

roles/aac/configure_api_protection_clients/molecule/add/verify.yml, roles/aac/configure_api_protection_clients/molecule/update/verify.yml, roles/aac/configure_api_protection_clients/tasks/main.yml, roles/aac/configure_authentication_policies/molecule/add/verify.yml, roles/aac/configure_authentication_policies/molecule/update/verify.yml, roles/aac/configure_server_connections/molecule/add/verify.yml, roles/aac/configure_server_connections/molecule/update/verify.yml, roles/aac/disable_all_authentication_policies/molecule/default/verify.yml, roles/aac/get_authentication_policies_by_name/molecule/default/converge.yml, roles/aac/get_mapping_rules/meta/main.yml, roles/aac/get_mapping_rules/tasks/main.yml, roles/config_ntp/tasks/main.yml
* configure_api_protection_clients/molecule/add/verify.yml: added assertion on the returned name is defined.
* configure_api_protection_clients/molecule/update/verify.yml: added assertion that the returned name and companyUrl are defined.
* configure_api_protection_clients/tasks/main.yml: updated the example input
* configure_authentication_policies/molecule/add/verify.yml: updated the role name to get_authentication_policies_by_name during the task that get the policy.
* configure_authentication_policies/molecule/update/verify.yml: updated the role name to get_authentication_policies_by_name during the task that get the policy.
* configure_server_connections/molecule/add/verify.yml: fixed task name
* configure_server_connections/molecule/update/verify.yml: fixed task name
* …
=> Fixes in several roles

playbooks/aac/configure_user_registry.yml, roles/aac/configure_user_registry/defaults/main.yml, roles/aac/configure_user_registry/molecule/add/converge.yml, roles/aac/configure_user_registry/molecule/delete/converge.yml, roles/aac/configure_user_registry/molecule/set_pw/converge.yml, roles/aac/configure_user_registry/tasks/main.yml
role:
- help message
- added set_pw, get_all, get, add, delete  functionality
- use of exclude filter to have flat user_registry
- flexibel loop label
- lopp variable chaned "with_items" -> "loop"
- filter for registry_action
- molecule adjustments for inventory structure
=> Fix: configure_user_registry

roles/web/configure_reverseproxy_instances/tasks/main.yml
Adding other styles for inventory notations:
- yaml + list (for entries)
- yaml
=> Update: Help Documentation for configure_reverseproxy_instances

playbooks/base/configure_signer_certificates.yml, roles/base/configure_signer_certificates/defaults/main.yml, roles/base/configure_signer_certificates/meta/main.yml, roles/base/configure_signer_certificates/tasks/main.yml, roles/base/import_signer_certificates/defaults/main.yml, roles/base/import_signer_certificates/tasks/main.yml
new role with features:
- functions: get_all, get, load, import_cert, export_cert, delete possible
Fix: import_signer_certificates
role:
- rename loop dictionary from signer_certificates to import_signer_certificates
=> NewRole+Fix: configure_signer_certificates

playbooks/web/config_reverseproxy_aac.yml, roles/web/config_reverseproxy_aac/defaults/main.yml, roles/web/config_reverseproxy_aac/meta/main.yml, roles/web/config_reverseproxy_aac/tasks/main.yml
Role to configure existing reverse proxy instances for aac integration
with:
- help message
- examples
=> New role+playbook: config_reverseproxy_aac

playbooks/web/config_reverseproxy_mmfa.yml, roles/web/config_reverseproxy_mmfa/defaults/main.yml, roles/web/config_reverseproxy_mmfa/meta/main.yml, roles/web/config_reverseproxy_mmfa/tasks/main.yml
Role to configure existing reverse proxy instances for mmfa integration
with:
- help message
- examples
=> New role+playbook: config_reverseproxy_mmfa

playbooks/web/config_reverseproxy_oauth.yml, roles/web/config_reverseproxy_oauth/defaults/main.yml, roles/web/config_reverseproxy_oauth/meta/main.yml, roles/web/config_reverseproxy_oauth/tasks/main.yml
Role to configure existing reverse proxy instances for oauth integration
with:
- help message
- examples
=> New role+playbook: config_reverseproxy_oauth

playbooks/aac/configure_policy_information_points.yml, roles/aac/configure_policy_information_points/defaults/main.yml, roles/aac/configure_policy_information_points/meta/main.yml, roles/aac/configure_policy_information_points/tasks/main.yml
Role to configure policy information points (PIP) with:
- help message
- examples (JavaScript only, others TBD)
=> New role+playbook: configure_policy_information_points (PIP)

playbooks/base/configure_certificate_requests.yml, roles/base/configure_certificate_requests/defaults/main.yml, roles/base/configure_certificate_requests/meta/main.yml, roles/base/configure_certificate_requests/tasks/main.yml
Role+Playbook to configure certificate signing requests CSR with:
- help message
- examples
=> New role+playbook: configure_certificate_requests

playbooks/base/configure_personal_certificates.yml, roles/base/configure_personal_certificates/defaults/main.yml, roles/base/configure_personal_certificates/meta/main.yml, roles/base/configure_personal_certificates/tasks/main.yml
Role+Playbook to configure personal certificates with:
- help message
- examples
=> New role+playbook: configure_personal_certificates

roles/web/configure_kerberos/tasks/main.yml
Skip_missing on subsections and properties added to allow kerberos configuration to skip unecessary requirements.
=> Feature: Kerberos configuration subsections and properties not mandatory

requirements.txt
This PR is a follow up to an email sent to the maintainers of this certified collection notifying them of a few new changes that will be needed for the next Ansible Automation Platform release. Contained in this PR is an example python requirements file built specifically for your collection. You can elect to merge this as is and edit as needed or close the PR and use it as an example to base your own commit off of. If you have any questions about why this PR was sent or confused about its necessity, please don't hesitate to ask in the comments here or email us at ansiblepartners@redhat.com.
=> adding python requirements file

roles/install_fixpack/meta/main.yml, roles/install_fixpack/tasks/main.yml
* removed line 30 '- force | default(False) }fig' from meta/main.yml
* removed line 18 to 22 from tasks/main.yml
=> Changes in install_fixpack role.

roles/base/configure_interfaces/tasks/main.yml
configure_interfaces role was not passing allowManagement to the called action
=> Fix: configure_interfaces role

meta/runtime.yml, roles/meta/main.yml
Fixed lint errors in roles/meta/main.yml
=> Added new file: meta/runtime.yml

galaxy.yml, playbooks/base/configure_certificate_databases.yml, roles/base/configure_certificate_databases/defaults/main.yml, roles/base/configure_certificate_databases/meta/main.yml, roles/base/configure_certificate_databases/tasks/main.yml
NAME
configure_certificate_databases
DESCRIPTION
Role to configure certificate databases
STEPS
1) Configure certificate databases
2) Commit changes
EXAMPLES
ansible-playbook -i [...] playbooks/ansible_collections/base/configure_certificate_databases.yml // configure all certificate databases from inventory
ansible-playbook -i [...] playbooks/ansible_collections/base/configure_certificate_databases.yml -e cert_dbase_id=pdsrv // configure only certificate databases from inventory for pdsrv.kdb
// filter for specific action from a single inventory at runtime
ansible-playbook -i [...] playbooks/ansible_collections/base/configure_certificate_databases.yml -e db_action=get_all
ansible-playbook -i [...] playbooks/ansible_collections/base/configure_certificate_databases.yml -e db_action=get …
=> New Role+Playbook: Configure Certificate Databases

playbooks/aac/configure_fido2.yml, roles/aac/configure_fido2/defaults/main.yml, roles/aac/configure_fido2/meta/main.yml, roles/aac/configure_fido2/tasks/main.yml
NAME
configure_fido2
DESCRIPTION
Role to configure fido2 [metadata, registrations, relying-parties, u2f-migration]
STEPS
1) Configure fido2 configurations
2) Commit changes
EXAMPLES
ansible-playbook -i [...] playbooks/ansible_collections/aac/configure_fido2.yml
INVENTORY
==========
fido2_configurations:
- fido2_action: metadata.get_all
- fido2_action: metadata.get
name: metadata.json
- fido2_action: metadata.export_file
name: metadata.json
filename: files/fido2/metadata.json
- fido2_action: metadata.delete
name: metadata.json
- fido2_action: metadata.import_file
filename: files/fido2/metadata.json
- fido2_action: relying_parties.get_all
- fido2_action: relying_parties.get
name: DEMO
- fido2_action: relying_parties.search
name: DEMO
- fido2_action: relying_parties.delete
name: DEMO
- …
=> New Role+Playbook: configure_fido2

playbooks/web/configure_redis.yml, roles/common_handlers/handlers/main.yml, roles/web/config_reverseproxy_redis/README.md, roles/web/config_reverseproxy_redis/defaults/main.yml, roles/web/config_reverseproxy_redis/meta/main.yml, roles/web/config_reverseproxy_redis/tasks/main.yml
Role & playbook to configure Redis on webseal
close #157
=> Issue157 redis configuration

plugins/connection/isam.py
Please verify this fix before merging.
=> fix: need self._sub_plugin in __init__

roles/aac/configure_runtime_template_root/tasks/main.yml, roles/aac/disable_authentication_policies/molecule/default/verify.yml, roles/base/externalize_hvdb/tasks/main.yml, roles/base/first_steps/tasks/main.yml, roles/bootstrap_local/tasks/main.yml, roles/config_fed_dir/tasks/main.yml, roles/create_reverseproxy/tasks/main.yml, roles/execute_compare/tasks/main.yml, roles/externalize_hvdb_db2/tasks/main.yml, roles/first_steps/tasks/main.yml, roles/switch_auth/tasks/main.yml, roles/web/configure_management_root/tasks/main.yml, roles/web/configure_reverseproxy_junctions/tasks/include_junctions.yml, roles/web/configure_reverseproxy_junctions/tasks/main.yml
=> fix: replaced include: with include_tasks:

roles/aac/configure_runtime_template_root/tasks/include_sync_runtime_template_root.yml
=> fix: list not string

roles/config_snmp_monitoring_v3/defaults/main.yml, roles/config_snmp_monitoring_v3/meta/main.yml, roles/config_snmp_monitoring_v3/tasks/main.yml, roles/set_rsyslog_forwarder/defaults/main.yml, roles/set_rsyslog_forwarder/tasks/main.yml
Add config_snmp_monitoring_v3 role.
=> Add config_snmp_monitoring_v3

playbooks/base/delete_interfaces.yml, roles/add_static_route/meta/main.yml, roles/base/add_interfaces/tasks/main.yml, roles/base/configure_interfaces/tasks/main.yml, roles/common_handlers/defaults/main.yml
* playbooks/base/delete_interfaces.yml
* roles/add_static_route/meta/main.yml
* roles/base/add_interfaces/tasks/main.yml
* roles/base/configure_interfaces/tasks/main.yml
* roles/common_handlers/defaults/main.yml
=> fixes in multiple files
