playbooks/base/load_signer_certificates.yml, roles/base/load_signer_certificates/defaults/main.yml, roles/base/load_signer_certificates/tasks/main.yml
playbook:
role:
- add help messages
- adding default for check_remote=False (simple or advanced remote server certificate comparison)
simple: check only if label already exists in kdb
advanced: check appliance and remote certificate data
- add filter for kdb_id and server
=> Fix: load_signer_certificates

playbooks/base/configure_interfaces.yml, roles/base/configure_interfaces/defaults/main.yml, roles/base/configure_interfaces/meta/main.yml, roles/base/configure_interfaces/tasks/main.yml
playbook:
- remove example inventory (now part of the role)
role:
- adding default variable interfaces
- change delete_missing variable name
- help message
- modify skip logic
- add limit label and address
=> Fix: configure_interfaces

roles/base/configure_interfaces/tasks/main.yml
The function _get_interface is a private function not returning a valid ansible return object. Therefore the get_all function should be used instead and the corresponding filtering needed to be modified. For details review the commit message
=> BugFix: Delete missing IP from interfaces

playbooks/web/create_reverseproxy_instances.yml, roles/web/create_reverseproxy_instances/defaults/main.yml, roles/web/create_reverseproxy_instances/tasks/main.yml
playbook:
- remove example (moved to role function -e help=True)
role:
- adding help message
- adding filter inst_name to limit execution at runtime
- changing structure of inventory (easier to handle for various roles+playbooks)
from
inventory:
- inst_name: default
admin_id: sec_master
[...]
to
inventory:
- inst_name: default
configuration:
admin_id: sec_master
[...]
- modify loop label to support docker and appliance inventory
=> Fix: create_reverseproxy_instances

roles/base/configure_interfaces/tasks/main.yml
Running the playbook/role without "-e configure_interfaces_delete_missing=True" skips filling of variable ret_obj with appliance interfaces resulting in error "The conditional check 'ret_obj.data != []' failed. The error was: error while evaluating conditional (ret_obj.data != []): 'dict object' has no attribute 'data'"
Conditional check only needs to check for dict sub-element data.
Following checks have been done:
- running playbook with and without "-e configure_interfaces_delete_missing=True"
- running playbook with "-e configure_interfaces_delete_missing=True" and an additional ipv4 address on an appliance which was successfully deleted
=> Bug-Fix: Undefined variable check

playbooks/base/configure_dns.yml, roles/base/configure_dns/defaults/main.yml, roles/base/configure_dns/meta/main.yml, roles/base/configure_dns/tasks/main.yml
New Role and Playbook to configure dns.
The feature to use interface label instead of UUID depends on ibmsecurity pull request : https://github.com/IBM-Security/ibmsecurity/pull/264
=> +role/playbook: configure_dns

roles/base/activate_modules/defaults/main.yml
Without increased command timeout following error is often raised because appliance didn't respond within default command timeout (30s):  `An exception occurred during task execution. To see the full traceback, use -vvv. The error was: See the timeout setting options in the Network Debug and Troubleshooting Guide.
[...]
ansible.module_utils.connection.ConnectionError: command timeout triggered, timeout value is 30 secs.
[...]
`
Higher timeout's (because of network latency or slower appliances) should be increased by manually overwriting the default command timeout through inventory variables or environment variables.  Review plugins\connection\isam.py DOCUMENTATION section for details.
=> BugFix: [false positives] Increase command timeout

playbooks/web/configure_kerberos.yml, roles/web/configure_kerberos/defaults/main.yml, roles/web/configure_kerberos/meta/main.yml, roles/web/configure_kerberos/tasks/include_configure_subsections_properties_1st_level.yml, roles/web/configure_kerberos/tasks/include_create_realms_subsections_2nd_level.yml, roles/web/configure_kerberos/tasks/main.yml
+ playbook to call role
+ role with following available tasks:
1) import multiple kerberos keytab files (-e kerberos_action=import_keytabs)
2) Create realms (-e kerberos_action=create_realms)
3) Create Realms Subsections (1st level) (-e kerberos_action=create_subsections)
4) Create Realms Subsections (2nd level) (-e kerberos_action=create_subsections)
5) Configure Realms Subsection Properties (root level) (-e kerberos_action=configure_properties)
6) Configure Realms Subsection Properties (1st level) (-e kerberos_action=configure_properties)
7) Configure Realms Subsection Properties (2nd level) (-e kerberos_action=configure_properties)
8) Configure Defaults (-e kerberos_action=configure_defaults)
9) Configure Kerberos Domain Mapping (-e kerberos_action=configure_domains)
10) Configure …
=> +1 role/playbook: configure_kerberos

playbooks/base/change_admin_password.yml
new ansible 2.10.x will raise an error if 'when' is used on vars_prompt in the playbook change_admin_password.
vars_prompt already skips vars provided via --extra-vars (-e old_password or -e new_password)
=> BugFix: when on vars_prompt not supported

roles/base/configure_static_routes/tasks/main.yml
Default value on metrics for a default gateway should be 0 and not 1.
This change has no impact on the functionality.
=> DocumentationFix: default gw metric is 0

playbooks/base/configure_advanced_tuning_parameters.yml, roles/base/configure_advanced_tuning_parameters/defaults/main.yml, roles/base/configure_advanced_tuning_parameters/tasks/main.yml
playbook:
role:
- help message
- filter for key at runtime
=> Fix: configure_advanced_tuning_parameters

playbooks/web/delete_reverseproxy_instance.yml, roles/web/delete_reverseproxy_instance/defaults/main.yml, roles/web/delete_reverseproxy_instance/meta/main.yml, roles/web/delete_reverseproxy_instance/tasks/main.yml
delete single reverseproxy instance with previous get from specified appliance. If no reverse proxy is available nothing will be done.
=> NewTask: delete_reverseproxy_instance

playbooks/web/configure_reverseproxy_junctions.yml, roles/web/configure_reverseproxy_junctions/defaults/main.yml, roles/web/configure_reverseproxy_junctions/tasks/include_create_junctions.yml, roles/web/configure_reverseproxy_junctions/tasks/include_delete_junction_server_hostnames.yml, roles/web/configure_reverseproxy_junctions/tasks/include_delete_junctions.yml, roles/web/configure_reverseproxy_junctions/tasks/include_junctions.yml, roles/web/configure_reverseproxy_junctions/tasks/main.yml
playbook:
role:
- help message
- modified filter path
- modified captions
- modified loop key "with_items" -> "loop"
- modified logic to include junction server parameter
- fixed filter mechanism
=> Fix: configure_junction_servers

playbooks/aac/configure_api_protection_definitions.yml, roles/aac/configure_api_protection_definitions/molecule/add/converge.yml, roles/aac/configure_api_protection_definitions/molecule/add/verify.yml, roles/aac/configure_api_protection_definitions/molecule/update/converge.yml, roles/aac/configure_api_protection_definitions/molecule/update/verify.yml, roles/aac/configure_api_protection_definitions/tasks/main.yml, roles/aac/configure_api_protection_definitions/vars/main.yml
QuickFix:
- playbook role path corrected
- role inventory structure corrected (api_protection_definitions -> api_protection.definitions) (review: https://github.com/IBM-Security/isam-ansible-roles/tree/master/aac/configure_api_protection_definitions)
- molecule testing modified to meet previous inventory structure
=> Fix: configure_api_protection_definitions inventory structure

playbooks/aac/configure_api_protection_clients.yml, roles/aac/configure_api_protection_clients/defaults/main.yml, roles/aac/configure_api_protection_clients/molecule/add/converge.yml, roles/aac/configure_api_protection_clients/molecule/add/verify.yml, roles/aac/configure_api_protection_clients/molecule/update/converge.yml, roles/aac/configure_api_protection_clients/molecule/update/verify.yml, roles/aac/configure_api_protection_clients/tasks/main.yml, roles/aac/configure_api_protection_clients/vars/main.yml
QuickFix:
- playbook role path corrected
- role inventory structure corrected (api_protection_definitions -> api_protection.definitions & api_protection_clients -> clients inside api_protection.definitions) (review: https://github.com/IBM-Security/isam-ansible-roles/tree/master/aac/configure_api_protection_clients)
- molecule testing modified to meet previous inventory structure
=> Fix: configure_api_protection_clients inventory structure

plugins/modules/isamcompare.py, roles/fed/configure_instance_federations/defaults/main.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
Changed AnsibleConnectionFailure to ansible.module_utils.connection.ConnectionError.
Ignore files to ignore validate-modules:missing-gplv3-license during ansible-test sanity.
=> Fix in isamcompare.py and new Ignore files

plugins/modules/isamcompare.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.9.txt
* Updated isamcompare.py to use ImportError instead of ConnectionError. 
* Added to the tests/sanity/ignore files:
plugins/connection/isam.py pylint:super-with-arguments
plugins/connection/isam.py pylint:raise-missing-from
=> Fixes for issues found by ansible-test

roles/add_sysaccount_user/defaults/main.yml, roles/add_sysaccount_user/tasks/main.yml
New collection role crashes with "_Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=self.isam_server, force=False, id=\"id\", groups=[{'id': 'group_id'}]_", while Python code still has:
"def create(isamAppliance, id, password, groups=[], check_mode=False, force=False):" as its function definition.
This is to fix the missing "password" from the arguments sent to the API.
=> Fix add_sysaccount_user: password missing for API call

roles/base/configure_interfaces/tasks/main.yml
Additional Feature: Switching logic of named key: values to dynamic dict. As overrideSubnetChecking  is not present on ipv6 add function, this solution is more flexible in handling parameters.
=> BugFix: Adding missing parameter overrideSubnetChecking for interfaceconfiguration

roles/add_oauth_client/tasks/main.yml, roles/add_oauth_definition/defaults/main.yml, roles/add_oauth_definition/tasks/main.yml, roles/set_mapping_rule/tasks/main.yml, roles/set_oauth_client/tasks/main.yml, roles/set_oauth_definition/defaults/main.yml, roles/set_oauth_definition/tasks/main.yml
Add missing 'Reload Liberty Runtime' statement in a few AAC roles:
add_oauth_definition
set_oauth_definition
add_oauth_client
set_oauth_client
set_mapping_rule
=> Add missing 'Reload Liberty Runtime' statements

playbooks/base/extract_certificates.yml, roles/base/extract_certificates/tasks/main.yml
* in extract_certificates playbook: changed ibm.isam.base/extract_certificates to ibm.isam.base.extract_certificates.
* in extract_certificates role, removed the empty loop_control and added in the required parameter "password".
=> Fixes in extract_certifcates playbook and role

playbooks/web/config_reverseproxy_federations.yml, roles/web/config_reverseproxy_federations/defaults/main.yml, roles/web/config_reverseproxy_federations/meta/main.yml, roles/web/config_reverseproxy_federations/tasks/main.yml
INVENTORY
==========
instances:
[...]
- inst_name: default
[...]
federation_configurations:
- fed_action: config
federation_name: demo-fed
hostname: localhost
port: '443' # should be a string, otherwise error WGAWA0423E can occur
username: easuser
password: {{ '{{' }} vault_easuser_pwd {{ '}}' }} # ansible-vault secured pwd
reuse_acls: True
reuse_certs: True
[...]
- fed_action: unconfig
federation_name: demo-fed
==========
=> New Role+Playbook: config_reverseproxy_federations

roles/add_oauth_definition/tasks/main.yml, roles/add_sysaccount_user/tasks/main.yml, roles/fed/create_federation_partners/tasks/main.yml
* roles/add_oauth_definition/tasks/main.yml:27:23: colons: too many spaces before colon
* roles/add_sysaccount_user/tasks/main.yml:10:15: colons: too many spaces before colon
* roles/fed/create_federation_partners/tasks/main.yml:36:19: colons: too many spaces before colon
=> Fixed yamllint issues

plugins/connection/isam.py
This fixes the error message:
[WARNING]: The "ibm.isam.isam" connection plugin has an improperly configured remote target value, forcing "inventory_hostname" templated value instead of the string
For more information on the issue see https://github.com/ansible/ansible/pull/77844/commits/a50dcefc2c6417fd956a8d8dec32f763068a011b
=> added missing var entry to connection plugin

README.md, changelogs/fragments/188-enable_tls_verification.yml, galaxy.yml, playbooks/base/configure_management_ssl.yml, plugins/connection/isam.py, requirements.txt, roles/base/set_management_ssl_cert/tasks/main.yml
Updates to ibm.isam collection, so we can use TLS verification of the LMI connection by default.
=> 188 add ssl verification setting
